### ISSUE TITLE
What does a URL represent ?

### ISSUE THREAD

**Issue by heistings** [casatwy/CTMediator#21]
Thanks for your CTMediator, it is very impressive for me.

And there is a question coming into my mind, that is what does a URL represent?

In many apps, a URL, with host, path and action , stands for an individual page, which is commonly considered as a controller. Thus when we open a scheme, we will actually open a new page.

But in CTMediator, when we are trying to open a URL, we are actually calling a service method, without respect to what is serving backwards.

I'm wandering what will you do when you are trying to implement open url as page via CTMediator ?

**Comment by casatwy** [comment]
CTMediator provides this method:`- (id)performActionWithUrl:(NSURL *)url completion:(void(^)(NSDictionary *info))completion;`

if your url matches `scheme://target/action?params=blablabla`，it works perfectly.

but if your url does not match the pattern above, that means you need a specific `target-action` to handle all the url string, and navigate the request to correct page or dispatch the request to correct component.

==================

so, here is a `target-action` that you have to notice.

`target-action` is not merely a `service method`, it presents to engineers all the interface a component have, and the url is a reference to the `target-action` that you actually want.

for example:

component `A_component` have pages: `A_page1`,`A_page2`,`A_page3`, we say that a page equals to a view controller. 

and `A_component` have a target: `A_target`, it is a normal NSObject, and it has three methods that we call it action: `A_target_action_showPage1`,`A_target_action_showPage2`,`A_target_action_showPage3`.

===============

lets go through the process that if your url matches the pattern. Say we have a scheme named `demo`, and we have params: `id`.

the url should be: `demo://A_target/A_target_action_showPage1?id=123`. when you send this url to `- (id)performActionWithUrl:(NSURL *)url completion:(void(^)(NSDictionary *info))completion;`, and your project have `A_component` inside (usually as dependency).

the CTMediator will find `A_target` and call the action `A_target_action_showPage1` with the params `{@"id":@"123"}` as `NSDictionary`.

now in your implementation of `A_target`'s `A_target_action_showPage1`, what you have to do is initialize the `A_page1` and push/present this page.

===================

if your url does not match the pattern, all you need is a new target called `Target_URLHandler`, and have action `Action_dispatch`.

say that your url is `demo://lorem/Ipsum?param=bla&foo=bar`, when you receive this url in AppDelegate, just call `- (id)performTarget:(NSString *)targetName action:(NSString *)actionName params:(NSDictionary *)params shouldCacheTarget:(BOOL)` and the target is `URLHandler`, action is `dispatch`, params is `{@"url":@"demo://lorem/Ipsum?param=bla&foo=bar"}`.

in the implementation of `Action_dispatch`, you recognize the url and find the actually `target-action` is `A_target` - `A_target_action_showPage1`, so call this target-action by CTMediator, everything is done!

===================

We don't make the url refers to a actual ViewController, we make it refers to a `target-action`, that's the only difference, and they both work the same. 

but the `target-action` method have more benefit: 

1. if the url matches the pattern, we don't have to have a table file to record what url refers to which view controller.

2. if the view controller which binds to a url needs to change in the future ,all we have to do is just modify the code in action, no more pains in check whether the new viewcontroller can be called by the url.

3. if we want to do some specific things before present a page with url, we can do it in the action instead of do it in the view controller, which will make the view controller too massive to maintain.

**Comment by heistings** [comment]
@casatwy Thanks for your reply. Wrapping anything playing a role like `target-action` will benefit. Router, data pick logic injection, AB...etc. The url pattern has taken place of the mapper config file or  the runtime register.(That is what many people would like to do, being simple and stupid)

The key question deeply in my mind is does every url calling turns out to be a page ? Have you ever used a url as a logic service without view controller ?

**Comment by casatwy** [comment]
every url refers to a target-action in CTMediator, which
can show a page or call a service like upload data or anything you want.

that means the url dont have to be bind to a view controller, it all depends on how you code the action that a url refers to.

**Comment by nathanwhy** [comment]
If my url is `demo://chat/{groupId}?pwd=123`,
the `groupId` is parameter.

How to handle this kind of url?

**Comment by casatwy** [comment]
try to make it target-action like.
